### ISSUE TITLE
how to fix error : braid_completion.py

### ISSUE THREAD

**Issue by D-Mad** [chufengxiao/SketchHairSalon#5]
python braid_completion.py
Traceback (most recent call last):
  File "braid_completion.py", line 316, in <module>
    comp_sk = braid_model.completion(sk,s_num=3,w=1)
  File "braid_completion.py", line 294, in completion
    img = plot3D_line(strand_list)
  File "braid_completion.py", line 153, in plot3D_line
    img = mlab.screenshot()
  File "/home/dev_ml/anaconda3/envs/SketchHairSalon1/lib/python3.8/site-packages/mayavi/tools/figure.py", line 355, in screenshot
    out.shape = shape
ValueError: cannot reshape array of size 12 into shape (0,0,3)

**Comment by chufengxiao** [comment]
Hi, I re-run the code and it works correctly. Do you ensure the packages' versions are the same as ours (e.g. mayavi)? Do you run the code on the machine with GUI for rendering (screenshot) the 3D model? Or maybe you need to provide more details about the error.
